# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Deploy GH Page and NPM Package

on:
  push:
    branches: [ main ]

jobs:
  github_pages: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js (15)
      uses: actions/setup-node@v1
      with:
        node-version: '15'

    - name: Install Pacakges 
      run: npm i
      
    - name: Build & Deploy 
      run: npm run deploy

  schemantic_release:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js (15)
      uses: actions/setup-node@v1
      with:
        node-version: '15'

    - name: Install Pacakges 
      run: npm i
      
    - name: Build Step 
      env: 
        CI: "" 
      run: npm run build

    - name: Run Semantic Release
      run: npx semantic-release --dry-run
      env:
        NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
